name: NVIDIA API

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  nvidia:
    uses: ./.github/workflows/provider-template.yml

    with:
      provider-name: NVIDIA
      test-file: tests/providers/test_nvidia.py

    secrets:
      secret_1: ${{ secrets.NVIDIA_API_KEY }}
