name: OpenRouter API

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  openrouter:
    uses: ./.github/workflows/provider-template.yml

    with:
      provider-name: OpenRouter
      test-file: tests/providers/test_openrouter.py

    secrets:
      secret_1: ${{ secrets.OPENROUTER_API_KEY }}