name: Cerebras API

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  cerebras:
    uses: ./.github/workflows/provider-template.yml

    with:
      provider-name: cerebras
      test-file: tests/providers/test_cerebras.py

    secrets:
      secret_1: ${{ secrets.CEREBRAS_API_KEY }}