name: Cloudflare API

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  ai-studio:
    uses: ./.github/workflows/provider-template.yml

    with:
      provider-name: ai-studio
      test-file: tests/providers/test_cloudflare.py

    secrets:
      secret_1: ${{ secrets.CLOUDFLARE_API_KEY }}
      secret_2: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}