name: GitHub API

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  ai-studio:
    uses: ./.github/workflows/provider-template.yml

    with:
      provider-name: github
      test-file: tests/providers/test_github.py

    secrets:
      secret_1: ${{ secrets.GITHUB_API_KEY }}