name: Groq API

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  groq:
    uses: ./.github/workflows/provider-template.yml

    with:
      provider-name: groq
      test-file: tests/providers/test_groq.py

    secrets:
      secret_1: ${{ secrets.GROQ_API_KEY }}